wallpaper {
    monitor = eDP-1
    path = ~/.config/backgrounds/catppuccin_mocha_fw_int_2256x1504.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-4
    path = ~/.config/backgrounds/catppuccin_mocha_dell_ext_3440x1440.png
    fit_mode = cover
}

splash = false
